name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [noetic]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8,linux/amd64
          push: true
          tags: ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-latest
      - name: Build and push challenge image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8,linux/amd64
          file: Dockerfile.challenge
          build-args: |
            BASE_IMAGE=ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-latest
          push: true
          tags: ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-challenge
      - name: Build and push forclass image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64/v8,linux/amd64
          file: Dockerfile.forclass
          build-args: |
            BASE_IMAGE=ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-latest
          push: true
          tags: ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-forclass
      - name: Build and push nvidia image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          file: Dockerfile.nvidia
          build-args: |
            BASE_IMAGE=ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-latest
          push: true
          tags: ghcr.io/hsr-project/tmc_wrs_binary:${{ matrix.version }}-nvidia
